// Generated by https://quicktype.io

// export type TweetsPostedResponse = {
//   data: Tweet[];
// };

export type Tweet = {
  id: string;
  content: string;
  createdAt: string;
  updatedAt: string;
};
